### ISSUE TITLE
Error: "There was a problem preparing your Payment"

### ISSUE THREAD

**Issue by webhotdesigns** [afterpay/afterpay-woocommerce#10]
I just updated woo and the plugin this morning and now getting this at the checkout for afterpay?  Can anybody help please?  

I contacted Afterpay in Australia and they hadn't heard of that problem.  

It was working yesterday ....

**Comment by MattLyonsInfo** [comment]
I had the same error, but I found it only occurred on my $1 test item. When I changed my order value to $50, all was well. There is a minimum value which AfterPay works. I can't find what it is, but it's somewhere!

What order value were you trying?

**Comment by webhotdesigns** [comment]
I restored previous version of the website and all is working again. I tried it numerous times with different values and continually got the same issue. I assume it still is a bug within the plugin and woocommerce 3.0.  Also when I updated woo, I lost my shop page, it was there but completely blank. Very strange so for the time being I'm sitting back and waiting ... :-)

**Comment by stevenocta** [comment]
Hi @webhotdesigns & @MattLyonsInfo ,

The error described above are generic exception message. 
For a more detailed exception reporting, you can enable the logging functionality and refer to Afterpay logs under _wp-content/uploads/wc-logs/afterpay.log_

@MattLyonsInfo: The Payment Limits is under _WP Admin / WooCommerce / Settings / Checkout / Afterpay_
