### ISSUE TITLE
not working in checkout payment

### ISSUE THREAD

**Issue by sutandang** [afterpay/afterpay-woocommerce#4]
why in checkout page payment method not working?

**Comment by taoteh1221** [comment]
I can confirm that the afterpay plugin is not registering as a payment gateway in a standard up-to-date woocommerce/checkout/payment.php template (with wp core and all plugins fully up-to-date), for a client of mine who has just signed up to use afterpay as an alternate payment method. Furthermore, it's not a conflict with Paypal, as disabling the Paypal gateway and leaving the Afterpay gateway enabled still results in Afterpay not displaying as a payment option. My client needs a solution soon, or she may not go with Afterpay as an alternate merchant account.

Here is the basic standard code below, which is in a standard / up-to-date woocommerce/checkout/payment.php template, where your plugin should be outputting on the front end checkout page as a registered woocommerce payment gateway:

`
				if ( ! empty( $available_gateways ) ) {
					foreach ( $available_gateways as $gateway ) {
						wc_get_template( 'checkout/payment-method.php', array( 'gateway' => $gateway ) );
					}
				}
`

Any chance we can get a solution soon, so you all don't lose an unhappy Afterpay client here?

**Comment by Kirtan711** [comment]
I have installed woo commerce Version 3.0.3 and WordPress 4.7.3 and installed afterpay plugin and setup all things as per readme.txt file but I didn't show after pay option on the checkout page.

I have also tried with installed lower version of WordPress. 
the below code is already in my file payment.php file.

if ( ! empty( $available_gateways ) ) { foreach ( $available_gateways as $gateway ) { wc_get_template( 'checkout/payment-method.php', array( 'gateway' => $gateway ) ); } }

But I don't know why didn't show on the checkout page.

**Comment by taoteh1221** [comment]
@Kirtan711 It seems they may not automatically strip whitespace / carriage returns from the ends of the API key when added on the settings page (which could easily be done with PHP's trim() function). This seems to have been the issue with my client's site. Make sure you aren't doing a copy / paste with anything other than the API key, and not including whitespace / carriage returns from a copy / paste of the key you get from them in your email etc.

**Comment by fit-au** [comment]
Having the same issue as @taoteh1221 with Afterpay not appearing on the WooCommerce Product or Checkout. Also using latest versions of Woo/WP Core. Logs show authentication does not seem to be the issue. Afterpay option is just not appearing next to PayPal. has anyone got a solution for this as yet? Thanks in advance.

**Comment by stevenocta** [comment]
Hi everyone, 

If Afterpay not showing in the checkout, please do the following:

1. Ensure that Merchant ID and Key are correctly inserted in the Afterpay Settings (_Admin / WooCommerce / Settings / Checkout / Afterpay_), then save the Settings page.

2. When installing a fresh install, please try to refresh the Settings page and check if the Payment Limits are updated, that would indicates that the Merchant ID and Key are correct.

3. Afterpay would then show up on the checkout page as long as the transaction is within the Merchant Payment Limits.

Thank you very much.

**Comment by engrmostafijur** [comment]
Sir,  Please help GoEmerchant  payment method not show in Checkout page help me!!!!!!!!!
I feel upset !!!!  Help me ...  https://www.vocalboothtogo.com/checkout/  Help me !!!!!!! Please

**Comment by engrmostafijur** [comment]
sir,  exiting customer  try to buy some things and want to  give  payment  via credit cart  ... But it becomes hide or disappear.. Please any help for support quickly ...
 
 https://www.vocalboothtogo.com/checkout/ Help me !!!!!!! 

Please help me   !!!!!!!!!!!!!!

Regards
Mostafijur
