### ISSUE TITLE
Error in backend under woocommerce

### ISSUE THREAD

**Issue by edwingiliams** [afterpay/afterpay-woocommerce#8]
Hi 

I am receiving this error under woocommerce

Notice: Undefined property: stdClass::$minimumAmount in /home/........./public_html/sps/wp-content/plugins/afterpay-woocommerce-master/woocommerce-afterpay.php on line 809

Thanks

Edwin

**Comment by UpwardDog** [comment]
Hi there,

I am having the same issue as above, plus I have noticed that not all of my products have the AfterPay marketing details attached.

Cheers,
Chris

**Comment by stevenocta** [comment]
@edwingiliams: That is a Notice caused by the Minimum Amount not populated correctly. It will be fixed in the next release.

@UpwardDog: Yes, that is working as intended. The reason would be to prevent WooCommerce Variable product from having one variation above/under the payment limits.
